#!/bin/bash

DESCRIPTION="Capture video stream from web camera and send it to RTMP server"
COPYRIGHT="(C) Vladimir Stavrinov <vstavrinov@gmail.com> 2013"
VERSION=1.1.1

#set -x -v

PATH=/opt/bin:/bin:/usr/bin:/sbin:/usr/sbin
SELF="$(basename $0)"
PID="$(ps ho pid -C $SELF)"
PID=${PID/$$/}
PID=${PID/ /}
ETC="etc"

[ -r /$ETC/flashstreamer/default.conf ] &&
. /$ETC/flashstreamer/default.conf
[ -r /$ETC/flashstreamer/local.conf ] &&
. /$ETC/flashstreamer/local.conf
[ -r ~/.config/flashstreamer/custom.conf ] &&
. ~/.config/flashstreamer/custom.conf

usage ()
{
    echo "
    $DESCRIPTION

    Usage:

    $SELF [-vdhks] [-c CONF] [-l LOG] [-D DEVICE]

    -c CONF
        Config file 

    -D DEVICE
        Input device

    -l LOG
	Log file 
    -k 
       Kill
    -s 
       Status
    -h
	Help
    -v
	Verbose
    -V
	Version
    -d 
	Debug
    
    Files:
    /etc/$SELF_NAME.conf
	System wide config
    ~/.${SELF_NAME}rc
	User config, override system settings
    "
    exit
}

OPTERR=0
while getopts dD:l:c:ksvVh OPTION; do
    case $OPTION in
	d)
	    set -x -v
	    ;;
	c)
	    CONF=$OPTARG
	    . $CONF
	    ;;
	D)
	    DEVICE=$OPTARG
	    ;;
	l)
	    LOG=$OPTARG
	    ;;
	k)
	    [ -n "$PID" ] &&
	    for ROOT in "$PID"; do
		    kill $(progeny $ROOT | awk '{print $NF}')
	    done
	    exit
	    ;;
	s)
	    [ -n "$PID" ] &&
	    for ROOT in "$PID"; do
		    ps wwfo user,pid,nice,tt,stat,lstart,command $(progeny $ROOT)
	    done
	    exit
	    ;;
	v)
	    VERBOSE=true
	    ;;
	V)
	    echo "
	    $SELF $VERSION
	    ${VERBOSE:+$COPYRIGHT}
	    "
	    exit
	    ;;
	h)
	    usage
	    ;;
    esac
done
shift  $[$OPTIND - 1]


: ${RESOLUTION:="640x360"}
: ${FPS:="25"}
: ${THREADS:="4"}
: ${BITRATE:="1024k"}
: ${OUT_FORMAT:="flv"}
: ${CODEC:="flv"}
: ${HOST=:"localhost"}
: ${SERVER:="tcp://$HOST:6666"}
: ${CONVERTER:="avconv"}
: ${OTHER:=""}

: ${NICE:=-0}
: ${OWNER:="webcam"}
: ${IN_FORMAT:="video4linux2"}
: ${DEVICE:="/dev/video0"}
: ${STREAM_NAME:="webcam"}
: ${LOG:="/var/log/flashstreamer/${STREAM_NAME}.log"}

if ! sudo -A /bin/true -u $OWNER : 2> /dev/null; then
        echo "
        Insufficient privileges.
        You should have permission to run $CONVERTER as user $OWNER
        "
        exit 1
fi

if ! [ -d "$(dirname $LOG)" ]; then
	mkdir -pm g+ws "$(dirname $LOG)"
	chown $OWNER "$(dirname $LOG)"
fi

umask g+w
exec > $LOG 2>&1 
date
set -x
nice -n $NICE sudo -u $OWNER $CONVERTER \
	${VERBOSE:+-v info} \
	-threads $THREADS \
		-f $IN_FORMAT \
		$OTHER \
		-vf hqdn3d \
	-i $DEVICE \
	$AUDIO \
		-r $FPS \
		$FREQUENCY \
		-b $BITRATE \
		-vcodec $CODEC \
		-bufsize 0 \
		-f $OUT_FORMAT \
		-s $RESOLUTION \
		-metadata streamName=$STREAM_NAME \
	$SERVER

